version: '3.4'
volumes:
  npm_data:
  runtime_data:

networks:
  default:
    external:
      name: scratchapi_scratch_network

services:
  app:
    container_name: scratch-www-app
    hostname: scratch-www-app
    environment:
      - API_HOST=http://localhost:8491
      - FALLBACK=http://scratchr2-app:8080
      - USE_DOCKER_WATCHOPTIONS=true
    build:
      context: ./
      dockerfile: Dockerfile
    image: scratch-www:latest
    command: ./docker_entrypoint.sh npm start
    volumes:
      - type: bind
        source: ./
        target: /var/app/current
        volume:
          nocopy: true
      - type: bind
        source: ../scratch-gui
        target: /var/app/current/scratch-gui
        volume:
          nocopy: true
      - npm_data:/var/app/current/node_modules
      - runtime_data:/runtime
    ports:
      - "8333:8333"
